<!-- Вывод товара -->
<hr />
<div class="item-list">
<?php if (count($this->items)): ?>

<hr />
<?php foreach ($this->items as $item): ?>
    <div class="item-item">
        <div class="item-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
    	<div class="item-img"><?php if ( $item->get('item_photo') ): ?><a href='<?=$item->getHref();?>'><img src=/catalog/small/<?=$item->get('item_photo')?> border='0'/></a><?php endif; ?></div>
    	<div class="item-previw"><?=$item->get('item_preview')?></div>
    	<div class="item-price"><?php if ( $item->get('item_price') ): ?><?=$item->get('item_price')?> руб.<?php endif; ?></div>
    </div>
<?php endforeach; ?>
<?php else: ?>
По вашему запросу ничего не найдено.
<?php endif; ?>
</div>
<!--конец -->