<?=$this->element->description?>
<?php if (count($this->items)): ?>
<ul class="news-list">
<?php foreach ($this->items as $item): ?>
    <li class="news-item">
        <div class="news-date"><?=$item->get('date')?></div>
        <div class="news-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
        <p><?=$item->get('preview')?></p>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
Новости: <?=$this->paginationControl($this->items,'Sliding','partials/paginationControl.phtml')?>