<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>xCMS Error</title>
</head>
<body>
    <? if($this->exception instanceof Zend_Db_Table_Exception ):?>
    Неверные параметры подключения к БД<br/>
    Попробуйте <a href="/install/">переустановить систему</a>
    <?        endif;?>
  <h1>An error occurred</h1>
  <h2><?= $this->message ?></h2>

  <? if ('development' == APPLICATION_ENV): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?= $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?= $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><? var_dump($this->request->getParams()) ?>
  </pre>
  <? endif ?>

</body>
</html>
