<?=$this->element->description?>
<?php if (count($this->items)): ?>
<ul class="news-list">
<?php foreach ($this->items as $item): ?>
    <li class="news-item">
        <div class="news-date"><?=date_create($item->items['publish_date_from'])->format('d.m.Y');?></div>
        <div class="news-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
        <p><?=$item->items['news_preview']?></p>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<p><a href='/<?=$this->newsHref();?>/archive/'>Архив Новостей</a></p>
<p><a href='/<?=$this->newsHref();?>/rss/'>RSS</a></p>
<?php if($this->items->getTotalItemCount()>$this->items->getItemCountPerPage()):?>
Новости: <?=$this->paginationControl($this->items,'Sliding','partials/paginationControl.phtml')?>
<?php endif;?>