<link rel="stylesheet" type="text/css" href="/jquery_gallery/fancybox/css/box.css" media="screen" />
<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/jquery_gallery/fancybox/js/box.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$(".zoom").fancybox({
			'frameWidth': 600,
			'frameHeight': 400
		});
	});
</script>
<?=$this->element->text;?>
	<div class="step1">Авторизация</div>
	<div class="step2">Оформление</div>
	<div class="step3">Подтверждение</div>
<? if(count($this->items)>0): ?>
<form method="post" style="clear: both;">
	<table class="basket-list">
		<tr>
			<th></th>
			<th>Наименование</th>
			<th>Цена</th>
			<th>Кол-во</th>
			<th>Общая сумма</th>
			<th>Удалить</th>
		</tr>
		<? foreach($this->items as $id=>$item):?>
			<tr id="tr<?=$id;?>">
				<td><a class="zoom" href="/shop/big/<?=$item['values']->shop_item_image?>"><img src="/shop/small/<?=$item['values']->shop_item_image?>" class="steps_small_image"/></a></td>
				<td><?=$item['name'];?></td>
				<td><?=$item['price'];?> руб. </td>
				<td class="basket-count">
					<a class="more" onClick="incCount(<?=$id;?>)">↑</a>
						<input class="shk-count" title="изменить количество" maxlength="3" name="multiple[<?=$id;?>]" id="count<?=$id;?>" size="2" type="text" value="<?=$item['count'];?>">
					<a class="less" onClick="decCount(<?=$id;?>)">↓</a>
				</td>
				<!-- <td><input type="text" name="multiple[<?=$id;?>]" value="<?=$item['count'];?>" size="2"/> шт. </td> -->
				<td><?=$item['price']*$item['count'];?> руб. </td>
				<td>
					<a  onClick="delFromOrder(<?="'".$item['href']."'"?>, <?=$id;?>)"><img src="/images/delete.png"/></a>
				</td>
			</tr>
		<? endforeach;?>
			<tr>
				<th colspan="6" style="text-align: right;">Итого: <span id="shopCart"><?=$this->sum?></span> руб.</th>
			</tr>
	</table>
    <input type="submit" name="recalc" value="Пересчитать" style="float: left; background-color: #FF6E00; color: #FFF; border: 0; padding: 5px 10px; margin: 3px;cursor: pointer;"/>
</form>
<? if ($this->next): ?>
<form method="post" name="next">
    <input type="submit" value="Следующий шаг" name="next_step"  style="float: left;background-color: #FF6E00; color: #FFF; border: 0; padding: 5px 10px; margin: 3px;cursor: pointer;"/>
</form>
<? else:?>

		<div class="rega1" style="clear: both;">
			<div class="title">Есть аккаунт</div>
			<div class="auth">
				<form enctype="application/x-www-form-urlencoded" method="post" action="/users/index/view">
					<dl class="zend_form">
						<dt id="username-label"><label for="username" class="field">Логин</label></dt>
						<dd id="username-element">
							<input class="field" type="text" name="username" id="username" value="">
						</dd>

						<dt id="userpass-label"><label for="userpass" class="field">Пароль</label></dt>
						<dd id="userpass-element">
							<input class="field" type="password" name="userpass" id="userpass" value="">
						</dd>

						<dt id="login-label">&nbsp;</dt>
						<dd id="login-element">&nbsp;</dd>
						<input type="submit" name="login" id="enter" value="Войти">
					</dl>
				</form>
			</div>
		</div>

		<div class="rega2">
			<div class="title">Зарегестрироваться</div>
			<div class="rega-text">
				<p>Для тех, кто покупает впервые.Процедура несложна и займет не более полминуты.</p>
				<!-- <input id="rega" name="butt" type="submit" value="Регистрация">-->
				<a href="/Регистрация" id="rega">Регистрация</a>
			</div>
		</div>

	<?php if ( (bool) Zend_Registry::getInstance()->get( 'buy_without_reg' ) ){?>
		<div class="rega3">
			<div class="title">Без регистрации</div>
			<div class="auth0">
				<form method="post" action="/Регистрация">
					<label class="field">Имя:</label>
					<input class="field" type="text" name="user_name" id="user_name" value="" class="String input-text">
					<label class="field">E-mail:</label>
					<input class="field" type="text" name="user_email" id="user_email" value="" class="Email input-text">
					<input type="hidden" name="guest" value="true">
					<input id="continue" name="butt" type="submit" value="Продолжить">
				</form>
			</div>
		</div>
<!--
<form method="post" action="/user/register/guestReg">
    <p>Фамилия пользователя
	<input type="text" name="user_surname" id="user_surname" value="" class="String input-text"></p>
    <p>Email
	<input type="text" name="user_email" id="user_email" value="" class="Email input-text"></p>
    <p>
	<input type="submit" name="regbutton" id="regbutton" value="Сохранить"></p>
</form>
-->
	<?php }	?>


<? endif;?>
<? else :?>
	<table class="basket-list">
	<tr><th>Информация о заказе</th></tr>
	<tr><td>Заказ пуст</td></tr>
	</table>
<? endif;?>
