<?
$reg = Zend_Registry::getInstance();
if($reg->get( 'parse_content' )) {
	$matches = array();
	preg_match_all("/<!-- block\(([\S\s]+)\) -->/U", stripslashes($this->element->text), $matches, PREG_PATTERN_ORDER);
	
	if(count($matches) > 0)
		for($i=0 ; $i < count($matches[0]) ; $i++) {
			$params = split(',' , $matches[1][$i]);
			for($j=0;$j<count($params);$j++) {
				$params[$j] = str_replace("'", "", $params[$j]);
				$params[$j] = str_replace("\"", "", $params[$j]);
			}
			$res = call_user_func_array(array($this, 'block'), $params);
			$this->element->text = str_replace($matches[0][$i], $res, stripslashes($this->element->text));
		}
}

echo $this->element->text;
?>
