<!-- Описание категории -->
<?=$this->element->description?>

<!-- Вывод категорий -->
<?php if (count($this->cat)): ?>
<ul class="category-list">
<?php foreach ($this->cat as $item): ?>
    <li class="category-item">
        <div class="category-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
        <?php if ( $item->get('item_photo') ): ?><div><img src="/shop/kategory/<?=$item->get('item_photo')?>" /></div><?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<!-- Вывод товара -->
<?php if (count($this->items)): ?>
<hr />
<div class="item-list">
<?php $count = 0; $total_items = $this->items->getCurrentItemCount();?>
<?php foreach ($this->items as $item): ?>
	<?php if($count%2==0):?>
	<div style="clear:both">
	<?php endif; ?>
    <div class="item-item">
        <div class="item-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
    	<div class="item-img"><?php if ( $item->get('item_photo') ): ?><a href='<?=$item->getHref();?>'><img src=/shop/small/<?=$item->get('item_photo')?> border='0'/></a><?php endif; ?></div>
    	<div class="item-previw"><?=$item->get('item_preview')?></div>
    	<div class="item-price"><?php if ( $item->get('item_price') ): ?><?=$item->get('item_price')?> руб.<?php endif; ?></div>
    </div>
   <?php $count++; if($count%2==0 || $total_items==$count):?>
	</div>
	<?php endif; ?>
<?php endforeach; ?>
</div>
<div style="clear:both">
</div>

<?php endif; ?>
<?php if($this->items->getTotalItemCount()>$this->items->getItemCountPerPage()):?>
Страницы: <?=$this->paginationControl($this->items,'Sliding','partials/paginationControl.phtml', array('categoryUrl'=>$this->element->urlname))?>
<?php endif;?>
