<h1>Заказ №<?=$this->order_id?></h1>
<div><b>Дата заказа:</b> <?=$this->shop_order_date?></div>
<div><b>Заказчик:</b> <?=$this->user['user_name']?> <?=$this->user['user_surname']?></div>
<div><b>Телефон:</b> <?=$this->shop_order_phone?></div>
<div><b>E-mail:</b> <?=$this->user['user_email']?></div>
<div><b>Метод доставки:</b> <?=$this->deliveryname?></div>
<div><b>Город доставки:</b> <?=$this->cityname?></div>
<div><b>Адрес доставки:</b> <?=$this->shop_order_address?></div>
<div><b>Метод оплаты:</b> <?=$this->paymentname?></div>
<div><b>Комментарий:</b> <?=$this->shop_order_comment?></div>
<br/>
<hr/>
<br/>
<table border="1" cellpadding="5">
<tr>
<td>Наименование</td>
<td>Цена</td>
<td>Кол-во</td>
<td>Стоимость</td>
</tr>
<?foreach($this->elements as $element) {?>
<tr>
<td><?=$element['shop_order_itemname']?></td>
<td><?=$element['shop_order_item_price']?> р.</td>
<td><?=$element['shop_order_item_count']?></td>
<td><?=round($element['shop_order_item_price']*$element['shop_order_item_count'], 2)?> р.</td>
</tr>
<?}?>
</table>
<br/>
<hr/>
<br/>
<div><b>Сумма заказа:</b> <?=$this->shop_order_sum?> р.</div>
<div><b>Стоимость доставки:</b> <?=$this->deliverysum?> р.</div>
<div><b>Итого:</b> <?=$this->deliverysum+$this->shop_order_sum?> р.</div>