<script type="text/javascript">
	$(document).ready(function(){
		link = $('#robox_link').attr('href');
		setTimeout("delayedRedirect('"+link+"')", 10000);
	});

	function delayedRedirect(link) {
		document.location.href=link;
	}
</script>
<?php
	$auth = Zend_Auth::getInstance();
	$user = Model_Collection_Users::getInstance()->getEntity($auth->getIdentity()->id);
	$user = $user->getValues();
?>
<div class="step1ok">Авторизация</div>
<div class="step2ok">Оформление</div>
<div class="step3ok">Подтверждение</div>

<div class="thx">
	<p class="tnxname"><span><?=$user['user_name']?></span>, cпасибо за покупку.</p>
	<p>На Ваш e-mail: <span><?=$user['user_email']?></span> был выслан запрос для подтверждения покупки.<br> После получения от Вас подтверждения наши менеджеры свяжутся с вами.</p>
</div>

<?if(isset($this->robox_link)):?>
	<div>Сейчас Вы будете перенаправлены на страницу оплаты. Если ничего не произошло в течение 30 секунд, перейдите по <a href="<?=$this->robox_link?>" id="robox_link">этой ссылке</a></div>
<?endif;?>