<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/cms/resources/jquery/ui/jquery-ui-1.8.1.custom.js"></script>
<script type="text/javascript">

jQuery().ready(function(){
  $('#faq').accordion({    
    alwaysOpen: true, 
    autoHeight: false 
 }); 
})

</script> 

<?=$this->element->description?> 
<?php
if ( isset($this->sent) ) {
	if ($this->sent)
		echo 'Ваш вопрос был успешно отправлен.';
	else
		echo 'Произошла ошибка при сохранении вашего вопроса, попробуйте еще раз позже.';
} elseif ( $this->form ) {
	echo $this->form->render();
}
?>
<?php if (count($this->items)): ?>
<div id="faq">
<?php foreach ($this->items as $item): ?>	
    	 	<h3><a href="#"><?=$item->items['faq_question']?></a></h3>
    	 	<div><?=$item->items['faq_answer']?></div>   	
<?php endforeach; ?>
</div>
<?php endif;?>
<?php if($this->items->getTotalItemCount()>$this->items->getItemCountPerPage()):?>
Страницы: <?=$this->paginationControl($this->items,'Sliding','partials/paginationControl.phtml')?>
<?php endif;?>