<?=$this->element->description?>
<?php if (count($this->items)): ?>
<ul class="articles-list">
<?php foreach ($this->items as $item): ?>
    <li class="articles-item">
        <div class="articles-title"><?=$this->navigation()->menu()->htmlify($item)?></div>
        <p><?=$item->get('preview')?></p>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<?php if($this->items->getTotalItemCount()>$this->items->getItemCountPerPage()):?>
Страницы: <?=$this->paginationControl($this->items,'Sliding','partials/paginationControl.phtml')?>
<?php endif;?>