<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<html> 
<head>
	<?=$this->headTitle()?>  
	<?=$this->headMeta()?> 
	<link href="/cms/css/base.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="wrap">
	<div id="logoMain"></div>
	<div id="text">
	<p class="error">
	Внимание!
	</p>
	<p>
	Установка CMS Фабрика сайтов, успешно выполнена. 
	Дальнейшее использование данного мастера установки 
	невозможно. Предлагаем перейти на 
	главную страницу сайта.
	</p>
	<div class="link_install">
	<a href="/">На главную</a>
	<img src="/cms/images/arrowOrangeRight.gif" class="arrow"/>
	</span>
	</div>
	
	</div>
</body>
</html>