<?=$this->element->text;?>
<? if(!$this->is_regist ): ?>
<? if( is_array($this->register_errors) ):?>
    <? foreach($this->register_errors as $key=>$error):?>
        <? foreach($error as $message):?>
            <b><?=$this->form->$key->getLabel();?></b>: <?=$message;?><br/>
        <? endforeach;?>
    <? endforeach;?>
    <?    endif;?>

<form method="post">
    <p>Логин <?=$this->form->login;?></p>
    <p>Пароль <?=$this->form->user_password;?></p>
    <p>Имя пользователя <?=$this->form->user_name;?></p>
    <p>Фамилия пользователя <?=$this->form->user_surname;?></p>
    <p>Email <?=$this->form->user_email;?></p>
    <p><?=$this->form->regbutton;?></p>
</form>
<? else : ?>
Регистрация прошла успешно
<? endif;?>

